site_name: Conta Digital
repo_url: https://github.com/thiagomeller/pipeline-conta-digital

nav:
  - Introdução: index.md
  - Transformações: transformacoes.md
  - Apresentação: apresentacao.md
  - Sobre: sobre.md

theme:
  name: material
  palette:
    primary: light-green
    accent: green
  language: pt
  features:
    - navigation.footer
    - navigation.path
    - navigation.paging
    - navigation.expand
    - navigation.top
    - navigation.sidebar
    - navigation.next-prev
    - navigation.toc
    - navigation.scrollspy
    - search
    - content.code.copy
    - content.code.select
  icon:
    logo: fontawesome/solid/code
    repo: fontawesome/brands/github

hide:
  - search
  - navigation
  - toc

extra:
  social:
    - icon: fontawesome/brands/mastodon 
      link: https://jl2tech.com
  generator: false

copyright: Copyright &copy; 2024 - <a href="#" target="_blank"><b>Thiago Meller Casagrande</b></a> - Todos os direitos reservados.

extra_css:
  - stylesheets/extra.css

markdown_extensions: 
    - admonition
    - codehilite
    - footnotes
    - meta
    - toc
    - pymdownx.highlight:
        anchor_linenums: true
        line_spans: __span
        pygments_lang_class: true
    - pymdownx.inlinehilite
    - pymdownx.snippets
    - pymdownx.superfences
    - pymdownx.details
    - md_in_html
    - pymdownx.snippets
    - pymdownx.emoji:
          emoji_index: !!python/name:materialx.emoji.twemoji
          emoji_generator: !!python/name:materialx.emoji.to_svg